# Generated by Django 4.0.5 on 2022-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor por hora')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por mês')),
            ],
        ),
    ]
