# Generated by Django 4.0.5 on 2022-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mensagem', models.TextField()),
                ('receber_noticias', models.BooleanField()),
            ],
        ),
    ]
