# Generated by Django 3.0.4 on 2020-04-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mesagem',
            new_name='mensagem',
        ),
    ]
