# Generated by Django 4.0.5 on 2022-07-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovRotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(verbose_name='Checkin')),
                ('checkout', models.DateTimeField(blank=True, null=True, verbose_name='Checkout')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor por hora')),
                ('pago', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_rotativo_veiculo', to='veiculos.veiculo', verbose_name='Valor por hora')),
            ],
        ),
    ]
