# Generated by Django 4.0.5 on 2022-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_rotativos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movrotativo',
            name='valor_hora',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='placa',
            field=models.CharField(default=1, max_length=8, verbose_name='Placa do veículo'),
            preserve_default=False,
        ),
    ]
