# Generated by Django 4.0.5 on 2022-07-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_rotativos', '0002_remove_movrotativo_valor_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movrotativo',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valor pago'),
            preserve_default=False,
        ),
    ]
