# Generated by Django 4.0.5 on 2022-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_rotativos', '0003_movrotativo_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor pago'),
        ),
    ]
