# Generated by Django 4.0.5 on 2022-07-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensalistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_em', models.DateField(verbose_name='Pago em')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor pago')),
                ('mensalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_mensalista_mensalista', to='mensalistas.mensalista', verbose_name='Mensalista')),
            ],
        ),
    ]
